#server:
#  address: 192.168.68.171

spring:
  task:
    scheduling:
      thread-name-prefix: scheduling-
      pool:
        size: 10
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tnt
    username: root
    password: # no password
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: messages.messages
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 25MB

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /api/docs
    operationsSorter: method